name: npm
on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build dependencies
        run: docker-compose build

      - name: Convert files
        run: docker-compose up

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          package: dist/package.json
          token: ${{ secrets.NPM_TOKEN }}